[package]
name = "zfs"
version = "0.1.0"
edition = "2021"

[lib]
name = "zfs"
path = "src/lib.rs"

[[bin]]
name = "zfs"
path = "src/main.rs"

[dependencies]
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
strum = { version = "0.24", features = ["derive"] }